### ISSUE TITLE
garbled screen

### ISSUE THREAD

**Issue by depperson** [adafruit/Mini-LED-Gamer#1]
Hi, I've built the mini gamer hardware but the screen is always garbled. The brightness buttons are the only function that works. Something seems to be wrong with the communication to the HT16k33. I tried using the matrix16x8 example from the Adafruit LED Backpack Library and it works  correctly. A number of other users on the linked forum pages have this same unanswered issue. 

http://forums.adafruit.com/viewtopic.php?f=22&t=76332&p=426985

**Comment by tvoverbeek** [comment]
Found the problem. See my answer on the forum:
https://forums.adafruit.com/viewtopic.php?f=22&t=76332&start=15#p435969

**Comment by Jianan-Li** [comment]
"Garbled screen" bug fixed and pull request created.

**Comment by Jianan-Li** [comment]
Pull request merged.
